config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  root to:"posts#index"
  namespace :posts do
    resources :searches, only: :index
  end
  resources :users, only: [:index, :show]
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:index, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user 
  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, :image, presence: true
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(search)
    return Post.all unless search
    Post.where(['title LIKE ? OR body LIKE ?', "%#{search}%", "%#{search}%"])
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :images
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configre_permitted_parameters, if: :devise_controller?
  
  def configre_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only:[:create, :destroy]

  def index
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @user = current_user

  end

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  def index
    @posts = Post.search(params[:keyword]).order(created_at: :desc)
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :create]
  before_action :move_to_index, except: [:index, :show, :search, :new, :destroy, :edit, :create, :update]
  before_action :user
  
  def index
    @posts = Post.all.order(created_at: :desc)
 
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def search
    @items = Item.search(params[:keyword])
    @posts = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end
  


  def create
    @post = Post.new(post_params)  
    if @post.save
      redirect_to root_path
    else
      render :new
    end

  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :new
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def user
    @user = current_user
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :name).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts/searches_helper.rb
module Posts::SearchesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang =ja>
  <head>
    <title>Japanapp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless post.like_user(current_user.id).blank? %>
    <%= link_to post_like_path(post_id: post.id ,id: post.likes[0].id), style: 'text-decoration :none; ', method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="material-icons red-text" >❤︎</i>
        <span class="red-text">
          <%= post.likes_count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), style: 'text-decoration :none;', method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="material-icons grey-text text-darken-2">♡</i>
        <span class="grey-text text-darken-2">
          <%= post.likes_count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% if post.likes_count > 0 %>
    <div class="vertical_like">
      <i class="material-icons red-text">❤︎</i>
      <span class="red-text">
        <%= post.likes_count %>
      </span>
    </div>
  <% else %>
    <div class="vertical_like">
      <i class="material-icons grey-text text-darken-2">♡</i>
      <span class="grey-text text-darken-2">
        <%= post.likes_count %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/index.html.erb
<%= render partial: "posts/header" %>
<div class="container">
<div class = "best3">
<h1 class ="best3sentense">Best 3</h1>
</div>
<div class="row">


  <%@all_ranks.each.with_index(1) do |post, i| %>
<div class="col-md-4 card bg-black margin-top-7per  like-card">

<div class="img_wrap">
<%= link_to post do%>

  <%= image_tag post.image.url, class: 'card-img',alt: "Card image",style: "height: 393px;" %>


  <div class="card-img-overlay">

<div class="fusen" style="padding-left: 60px;">
<ul>
  <li> <%= i%></li>

</ul>
</div>


    <h4 class="card-title" ><%= post.title %></h4>
 
    <p class="card-text"><%=post.created_at.strftime('%Y/%m/%d')%></p>
    <p class="card-text like-view">
    ♡<%=post.likes_count%>
    </p>

  
    <p class="card-text">
  
    </p>
  </div>
</div>
<% end %>
</div>
<%end%>
</div>
</div>
<%= render partial: "posts/footer" %>

app/views/posts/_footer.html.erb
 <footer class="bg-danger" >
      <ul class="list-inline text-center py-2">
        <li class="list-inline-item">
          <a href="" class="text-white"></a>
        </li>
        <li class="list-inline-item">
          <a href="" class="text-white"></a>
        </li>
        <li class="list-inline-item">
          <a href="" class="text-white"></a>
        </li>
      </ul>
      
      <div class="text-white text-center pb-4">
        <p class="h2">goodjapan</p>
        <small class="small">&copy;created by Kaito Nishimura</small>
      </div>
      
    </footer>

app/views/posts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class ="navbar-brand" href="/">goodjapan</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>


        <li class="nav-item ">
          <%= link_to new_post_path, class: "nav-link" , style:" font-family: Comic Sans MS;" do %>
            <i class ="far fa-file-alt"></i>post
          <% end%>
        </li>


        <li class="nav-item">
          <%= link_to user_path(current_user) , class: "nav-link" do %>
          ♡<%= @user.nickname %>'s Like
          <%end%>
        </li>

        <li class="nav-item">
          <%= link_to post_likes_path(:post_id), class: "nav-link" do %>
          <i class="fas fa-crown"></i>ranking
          <% end%>
        </li>

        <li class="nav-item">
          <%= link_to destroy_user_session_path,data: {confirm: 'ログアウトしますか？'}, method: :delete,  class: "nav-link" do %>
        <i class="fas fa-sign-out-alt"></i>log out
          <% end %>
        </li>

        <% else %>

        <li class="nav-item">
          <%= link_to  new_user_registration_path, class: "nav-link" do%>
          <i class="fas fa-user-plus"></i>sign up
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do%>
          <i class="fas fa-sign-in-alt"></i> log in
          <% end %>
        </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/posts/_post.html.erb
<div class="col-md-3 card bg-black margin-top-5per">



<div class="img_wrap">
<%= link_to post do%>
  <%= image_tag post.image.url, class: 'card-img',alt: "Card image" %>

  <div class="card-img-overlay">

    <h4 class="card-title" 
    ><%= post.title %></h4>
    <p class="card-text"><%=post.created_at.strftime('%Y/%m/%d')%></p>
    <p class="card-text like-view">
    ♡<%=post.likes_count%>
    </p>

  
    <p class="card-text">
    <%=@post_like %>
    

    </p>
  </div>

</div>
<% end %>
</div>

app/views/posts/edit.html.erb
<%= render partial: "header" %>
  <div class ="container">
    <div class ="col-md-12 margin-top-5per book-block">
      <div class = "padding-bottom-15">
        <%= form_for(@post) do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title , placeholder: 'type a title', class:'form-control' %>
          </div>
            <div class="form-group, form-group-file">
              <%= f.label :image, style:"cursor: pointer;" do%>
              <i class="far fa-file-image"></i>
              <%= f.file_field :image ,class: "file-select" %>
              <% end %>
            </div>
              <div class="form-group" >
                <%= f.text_area :body, placeholder: "text" , rows: "3", class:'form-control' %>
            </div>
          <%= f.submit "edit", class: 'send-btn'%>
        <% end %>
      </div>
    </div>
  </div>
<%= render partial: "footer" %>

app/views/posts/index.html.erb
<%= render partial: "header" %>
<div class = "search">
<%= form_with(url: posts_searches_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "ex) tokyo", class: "search-input" %>
  <%= form.submit "push", class: "search-btn" %>
</div>
<% end %>
<div class="container">
<div class="row">
  <% @posts.each do |post| %>
    <%= render partial: "post", locals: { post: post } %>
  <% end %>
</div>
</div>

<%= render partial: "footer" %>

app/views/posts/new.html.erb
<%= render partial: "header" %>
  <div class ="container">
    <div class ="col-md-12 margin-top-5per book-block">
      <div class = "padding-bottom-15">
        <%= form_for(@post) do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title , placeholder: 'type a title', class:'form-control' %>
          </div>
            <div class="form-group form-group-file">
              <%= f.label :image, style:"cursor: pointer;" do%>
                <i class="far fa-file-image"></i>
                <%= f.file_field :image ,class: "file-select"%>
            <% end %>
            </div>
              <div class="form-group" >
                <%= f.text_area :body, placeholder: "text" , rows: "3", class:'form-control' %>
              </div>
                <%= f.submit "post", class: 'send-btn'%>
            <% end %>
      </div>
    </div>
  </div>
<%= render partial: "footer" %>

app/views/posts/searches/index.html.erb
<%= render partial: "posts/header" %>
<div class ="search">
<%= form_with(url: posts_searches_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "ex) Tokyo", class: "search-input" %>
  <%= form.submit "push", class: "search-btn" %>
</div>
<% end %>
<div class="container">
<div class="row">
<%if @posts.present?%>
<% @posts.each do |post| %>
<div class="col-md-3 card bg-black margin-top-5per">
<div class="img_wrap">
<%= link_to post do%>
  <%= image_tag post.image.url, class: 'card-img',alt: "Card image" %>

  <div class="card-img-overlay">

    <h4 class="card-title" ><%= post.title %></h4>
    <p class="card-text"><%=post.created_at.strftime('%Y/%m/%d')%></p>
    <p class="card-text like-view">
    ♡<%=post.likes_count%>
    </p>

    <p class="card-text">
    <%=@post_like %>
    

    </p>
  </div>

</div>
<% end %>
</div>


  <% end %>

  <% else %>
no results
  <%end%>

</div>

</div>

<%= render partial: "posts/footer" %>

app/views/posts/show.html.erb
<%= render partial: "header" %>
  <div class ="container">
    <div class="col-md-12 card margin-top-5per  margin-bottom-5per book-block">
      <%= image_tag @post.image.url, class: 'post-image' %>     
        <h3 class = "text-center"><%= @post.title%></h3>
          <div class = "padding-bottom-15">
            <div class = "time-like">

            <div id="likes_buttons_<%= @post.id %>">
 <%= render partial: 'likes/like', locals: { post: @post, likes: @likes} %>
</div>
          <div class = "created_at"> <%= @post.created_at.strftime('%Y/%m/%d')%>

            </div>
              </div>
              <div class= "text-center title"><%= @post.body%></div> 

              <div class = "edit-delete">
                <% if user_signed_in? && current_user.id == @post.user_id %>
                  <%= link_to edit_post_path(@post) , style: 'color: lightgrey; text-decoration :none; font-size: 30px;' do%>
                  <i class="fas fa-edit"></i>
                  <% end %>   
                  <%= link_to post_path(@post), method: :delete, data: {confirm: '削除しますか？'}, style: 'color: lightgrey; text-decoration :none; font-size: 30px;' do%>
                  <i class="far fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </div>

          </div>
        </div>
          <div class ="col-md-12 card margin-top-5per  margin-bottom-5per book-block">
            <% if current_user %>
              <%= form_with(model: [@post, @comment], local: true, id: "new_comment") do |form| %>
                <%= form.text_area :text, placeholder: "type comments", rows: "2",class:'form-control', style: 'margin-top: 20px;' %>
                <%= form.submit "SEND", style: 'margin-top: 10px;', class:'send-btn' %>
              <% end %>
            <% else %>
              <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
            <% end %>
              <div class="comments">
                <div class = "view-comments">
                <h4 class = "text-center">＜comments＞</h4>
                </div>
                  <% if @comments %>
                    <% @comments.each do |comment| %>
                      <p>
                        <strong><%=  comment.user.nickname %>：</strong>
                        <%= comment.text %>
                      </p>
                    <% end %>
                  <% end %>
              </div>
            
            
    </div>  
  </div>
<%= render partial: "footer" %>

app/views/users/show.html.erb
<%= render partial: "posts/header" %>

<div class="container">
<div class="row">
  <% @user.liked_posts.each do |post| %>
<div class="col-md-3 card bg-black margin-top-5per">



<div class="img_wrap">
<%= link_to post do%>
  <%= image_tag post.image.url, class: 'card-img',alt: "Card image" %>

  <div class="card-img-overlay">

    <h4 class="card-title" 
    ><%= post.title %></h4>
    <p class="card-text"><%=post.created_at.strftime('%Y/%m/%d')%></p>
    <p class="card-text like-view">
    ♡<%=post.likes_count%>
    </p>

  
    <p class="card-text">
    <%=@post_like %>
    

    </p>
  </div>

</div>
<% end %>
</div>
  <% end %>
</div>
</div>

<%= render partial: "posts/footer" %>